services:
  app:
    build: .
    container_name: betting-app
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongo1:27017,mongo2:27018,mongo3:27019/betting?replicaSet=rs0
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - redis

  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1-data:/data/db

  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2-data:/data/db

  mongo3:
    image: mongo:6
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3-data:/data/db

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
